### ISSUE TITLE
When invalid Hex provided...

### ISSUE THREAD

**Issue by AlfredJKwack** [lffg/yiq#3]
Hi,

While considering options for YIQ I came across your lib. It looks good at first glance, great work. 

I did notice that the library arbitrarily returns `#fff` when an invalid Hex value is thrown at it ([#L23-L25](https://github.com/lffg/yiq/blob/181a153821cd5d9945041047e2ff760658670961/index.js#L23-L25)). 

Might I suggest you provide at least a console warning or something. Additionally, it would be nice if this condition were trappable and covered by a test case too. Lastly, why not return `options.white` instead of an arbitrary `#fff`?

Something like the below would be a great start:

```
  if (! /(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)/i.test(colorHex)) {
    console.warn(`You provided colorHex ${colorHex}, which isn't a valid Hex value`);
    return '#fff'
  }
```

Thanks for the consideration.

**Comment by lffg** [comment]
Hello,

Thanks for the feedback.
I agree with all your points, and thanks again for pointing them out. Do you want to open a PR for that? If not, I'll _fix_ it myself.

**Comment by lffg** [comment]
Closing since all the mentioned points were reviwed in the new major version.

Ref: https://github.com/lffg/yiq/pull/5
